# Generated by Django 5.1.2 on 2024-11-02 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EducationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('direct_use', models.BooleanField()),
                ('generic_dependancies', models.ManyToManyField(to='student_analyze.educationgroup')),
                ('educationstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.educationstate')),
            ],
        ),
        migrations.CreateModel(
            name='EducationGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('educationstate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.educationstate')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('educationgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.educationgrade')),
                ('educationgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.educationgroup')),
                ('grade_base_prerequisite', models.ManyToManyField(to='student_analyze.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('birth_date', models.DateField()),
                ('national_code', models.IntegerField(unique=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.gender')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('education_groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.educationgroup')),
                ('education_states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.educationstate')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.educationgrade')),
                ('education_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.educationgroup')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.person')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.school')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.person')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.school')),
            ],
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('educationgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.educationgrade')),
                ('educationgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.educationgroup')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.lesson')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.school')),
                ('students', models.ManyToManyField(to='student_analyze.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_analyze.teacher')),
            ],
        ),
    ]
