# Generated by Django 5.1.2 on 2024-11-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_analyze', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='education_groups',
        ),
        migrations.RemoveField(
            model_name='school',
            name='education_states',
        ),
        migrations.AddField(
            model_name='school',
            name='education_groups',
            field=models.ManyToManyField(to='student_analyze.educationgroup'),
        ),
        migrations.AddField(
            model_name='school',
            name='education_states',
            field=models.ManyToManyField(to='student_analyze.educationstate'),
        ),
    ]
